# This workflow demonstrates how to output the different context objects

name: Variables and Context

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context

        # creating a local (just to this step) env variable
        env:
          GITHUB_CONTEXT: ${{toJson(github)}}
        run: echo "$GITHUB_CONTEXT"
